name: Docker Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: username/nextjs-app:latest

    - name: Deploy Docker container
      run: |
        docker pull username/nextjs-app:latest
        docker run -d -p 3000:3000 username/nextjs-app:latest
